server:
  port: 18081
# springcloud: nacos sentinel zipkin
# springboot: \u6570\u636E\u6E90 redis\u5730\u5740
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.116.100:3306/guli_pms
    username: root
    password: root
  redis:
    host: 172.16.116.100
  rabbitmq:
    host: 172.16.116.100
    virtual-host: /fengge
    username: fengge
    password: fengge
    publisher-confirm-type: SIMPLE
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
feign:
  sentinel:
    enabled: true
# mybatis-plus\uFF1A\u6620\u5C04\u6587\u4EF6 \u522B\u540D\u626B\u63CF id\u7B56\u7565
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.atguigu.gmall: debug
